#! /bin/sh
# postinst script for byaccj

set -e

if [ $1 != "upgrade" ] ; then
	update-alternatives \
		--install /usr/bin/yacc yacc /usr/bin/byaccj 70
#		--slave /usr/share/man/man1/yacc.1.gz yaccman \
#			/usr/share/man/man1/byacc.1.gz
fi

#DEBHELPER#

exit 0
